#!/usr/bin/env python3
"""Build an auditable TWStock paper execution report.

This is a local report assembler. It does not submit orders, query databases,
connect to brokers, or mutate state. Inputs are JSON artifacts generated by the
Phase 4 paper pipeline, order read-back verifier, and paper portfolio summary.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Optional, Sequence


def load_json(path: str) -> Dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8")) if path else {}


def _nested(payload: Dict[str, Any], *keys: str, default: Any = None) -> Any:
    cur: Any = payload
    for key in keys:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    return cur


def build_report(*, pipeline: Dict[str, Any], verification: Dict[str, Any], portfolio_summary: Dict[str, Any]) -> Dict[str, Any]:
    preview = pipeline.get("preview") if isinstance(pipeline.get("preview"), dict) else {}
    submit = pipeline.get("submit") if isinstance(pipeline.get("submit"), dict) else {}
    summary_data = portfolio_summary.get("data") if isinstance(portfolio_summary.get("data"), dict) else portfolio_summary
    orders = preview.get("orders") or []
    payloads = submit.get("payloads") or []
    submit_results = submit.get("submit_results") or []
    failed_submits = [item for item in submit_results if not item.get("ok")]
    rejected_submits = []
    for item in submit_results:
        if not isinstance(item, dict) or not item.get("ok"):
            continue
        response = item.get("response") if isinstance(item.get("response"), dict) else {}
        data = response.get("data") if isinstance(response.get("data"), dict) else {}
        if str(data.get("status") or "").lower() == "rejected":
            rejected_submits.append(item)
    warnings = []
    warnings.extend(preview.get("warnings") or [])
    warnings.extend(submit.get("warnings") or [])
    warnings.extend(summary_data.get("warnings") or [])
    guard_errors = list(pipeline.get("guard_errors") or [])
    missing_uids = list(verification.get("missing_order_uids") or [])
    matched_uids = list(verification.get("matched_order_uids") or [])
    status = "pass"
    status_reasons = []
    if guard_errors:
        status = "fail"
        status_reasons.append("pipeline_guard_errors")
    if failed_submits:
        status = "fail"
        status_reasons.append("failed_submit_results")
    if missing_uids:
        status = "fail"
        status_reasons.append("missing_verified_orders")
    if rejected_submits and status == "pass":
        status = "warning"
        status_reasons.append("rejected_paper_orders")
    if warnings and status == "pass":
        status = "warning"
        status_reasons.append("warnings_present")
    order_digest = []
    for item in orders:
        if not isinstance(item, dict):
            continue
        order_digest.append({
            "symbol": item.get("symbol"),
            "side": item.get("side"),
            "qty": item.get("qty"),
            "order_type": item.get("order_type"),
            "limit_price": item.get("limit_price"),
            "reference_price": item.get("reference_price"),
            "status": item.get("status"),
            "estimated_notional": item.get("estimated_notional"),
        })
    return {
        "market": "TWStock",
        "paper_only": True,
        "status": status,
        "status_reasons": status_reasons,
        "safety": {
            "paper_only": True,
            "broker_connected": False,
            "live_order_submitted": False,
        },
        "pipeline": {
            "dry_run": bool(pipeline.get("dry_run")),
            "preview_order_count": _nested(pipeline, "preview_summary", "order_count", default=preview.get("order_count", 0)),
            "blocked_count": _nested(pipeline, "preview_summary", "blocked_count", default=preview.get("blocked_count", 0)),
            "submit_candidate_count": _nested(pipeline, "submit_summary", "submit_candidate_count", default=len(payloads)),
            "submitted_count": _nested(pipeline, "submit_summary", "submitted_count", default=len(submit_results)),
            "failed_submit_count": _nested(pipeline, "submit_summary", "failed_submit_count", default=len(failed_submits)),
            "rejected_submit_count": len(rejected_submits),
            "guard_errors": guard_errors,
        },
        "orders": order_digest,
        "submitted_payloads": payloads,
        "rejected_submit_results": rejected_submits,
        "verification": {
            "expected_count": verification.get("expected_count", 0),
            "matched_count": verification.get("matched_count", 0),
            "missing_count": verification.get("missing_count", 0),
            "matched_order_uids": matched_uids,
            "missing_order_uids": missing_uids,
        },
        "portfolio_summary": {
            "initial_cash": summary_data.get("initial_cash"),
            "cash": summary_data.get("cash"),
            "gross_buy_value": summary_data.get("gross_buy_value"),
            "gross_sell_value": summary_data.get("gross_sell_value"),
            "realized_pnl": summary_data.get("realized_pnl"),
            "open_cost_value": summary_data.get("open_cost_value"),
            "equity_at_cost": summary_data.get("equity_at_cost"),
            "position_count": summary_data.get("position_count"),
            "positions": summary_data.get("positions") or [],
        },
        "warnings": warnings,
    }


def render_markdown(report: Dict[str, Any]) -> str:
    lines = [
        "# TWStock Paper Execution Report",
        "",
        f"- Status: {report.get('status')}",
        f"- Market: {report.get('market')}",
        f"- Paper only: {report.get('paper_only')}",
        f"- Broker connected: {report.get('safety', {}).get('broker_connected')}",
        f"- Live order submitted: {report.get('safety', {}).get('live_order_submitted')}",
        "",
        "## Pipeline",
    ]
    for key, value in (report.get("pipeline") or {}).items():
        lines.append(f"- {key}: {value}")
    lines.extend(["", "## Verification"])
    for key, value in (report.get("verification") or {}).items():
        lines.append(f"- {key}: {value}")
    lines.extend(["", "## Portfolio Summary"])
    for key, value in (report.get("portfolio_summary") or {}).items():
        if key != "positions":
            lines.append(f"- {key}: {value}")
    lines.extend(["", "## Orders"])
    for order in report.get("orders") or []:
        lines.append(f"- {order.get('symbol')} {order.get('side')} {order.get('qty')} {order.get('order_type')} limit={order.get('limit_price')} status={order.get('status')}")
    lines.extend(["", "## Warnings"])
    warnings = report.get("warnings") or []
    if warnings:
        for warning in warnings:
            lines.append(f"- {warning}")
    else:
        lines.append("- none")
    return "\n".join(lines) + "\n"


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build TWStock paper execution report from Phase 4 JSON artifacts.")
    parser.add_argument("--pipeline-json", required=True)
    parser.add_argument("--verify-json", required=True)
    parser.add_argument("--portfolio-summary-json", required=True)
    parser.add_argument("--output-json", default="")
    parser.add_argument("--output-md", default="")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)
    report = build_report(
        pipeline=load_json(args.pipeline_json),
        verification=load_json(args.verify_json),
        portfolio_summary=load_json(args.portfolio_summary_json),
    )
    text = json.dumps(report, ensure_ascii=False, indent=2)
    print(text)
    if args.output_json:
        path = Path(args.output_json)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text + "\n", encoding="utf-8")
    if args.output_md:
        path = Path(args.output_md)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_markdown(report), encoding="utf-8")
    return 0 if report.get("status") in ("pass", "warning") else 1


if __name__ == "__main__":
    raise SystemExit(main())
